{
 "title": "ESXi Overview",
 "tags": [
  "esxi",
  "vmware"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "ESXi Host Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(host_name)( max_over_time(vmware_host_sensor_temperature[5m]) )"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * max_over_time(vmware_host_cpu_usage[5m]) / max_over_time(vmware_host_cpu_max[5m])"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * max_over_time(vmware_host_memory_usage[5m]) / max_over_time(vmware_host_memory_max[5m])"
    }
   ]
  }
 ]
}