name: Deploy WhatsApp Birthday Bot
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # For manual triggering
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/unit -v
        # Only run integration tests on main branch
        if [ ${{ github.ref == 'refs/heads/main' }} ]; then
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/integration -v
        fi
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AKIA5CBDQ2CCGTY2TXI7 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    
    - name: Build Docker images
      run: |
        cd docker
        docker build -t whatsapp-birthday-bot:latest -f Dockerfile.scheduler .
        aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com
        docker tag whatsapp-birthday-bot:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/whatsapp-birthday-bot:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/whatsapp-birthday-bot:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Only deploy on main branch
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve
    
    - name: Deploy React App
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - run: |
        cd web-ui/birthday-manager
        npm install
        npm run build
        aws s3 sync build/ s3://birthday-bot-ui-${{ secrets.AWS_ACCOUNT_ID }}
